bot:
  prefix: "$"
  licenseKey: "W6S55ZXMZNNSGVR8"
  embedColor: "#ffa201"
  voiceTimeoutMs: 1000
  voiceDataRetries: 20
  bufferDurationMs: 5000

database:
  mongodb:
    uri: "mongodb+srv://plantedpurpose:P2WDevelopments@cluster0.ppqhqte.mongodb.net/?appName=Cluster0"
    dbName: "cluster0"

webhooks:
  errors: "https://discord.com/api/webhooks/...."

lavalink:
  resumeKey: "FizzyStudio"
  resumeTimeout: 180
  retryDelay: 3000
  retryMax: 15
  nodes:
    - name: "Node-1"
      host: "us-node-2.altvr.in"
      port: 2088
      password: "youshallnotpass"
      secure: false
    
spotify:
  clientId: "CLIENT_ID"
  clientSecret: "CLIENT_SECRET"

sharding:
  enabled: false
  totalShards: 1
  respawn: true
  mode: process
